### ISSUE TITLE
[guide] Going to production

### ISSUE THREAD

**Issue by thibaultcha** [Kong/getkong.org#106]
- How many nodes for any amount of traffic
- How many Cassandra nodes for a Kong cluster
- How to distribute and/or scale Kong
- How to load balance your traffic on a Kong cluster
- How to setup a production ready Cassandra cluster (authentication/authorization/multi-region)
- How to setup your DNS records to leverage the `Host` header #87 
- How to upgrade Kong without downtime
- How and why to protect the Admin API (`8001`)
- How to link your users to Kong (`custom_id`)

**Comment by orliesaurus** [comment]
+1

**Comment by sinzone** [comment]
these questions can be in the FAQ too.

**Comment by Marak** [comment]
I'm evaluating using a Kong based solution for an existing enterprise which is already operating at a very large scale ( millions of requests per second ).

I see this issue hasn't been updated in some time.

Has this information been posted anywhere? Can you recommend any good resources for implementing Kong at scale?

**Comment by coopr** [comment]
Most of this has been documented - closing, though I could imagine more specific issues being opened in the future that ask for the parts of this that aren't yet completed well enough.
