### ISSUE TITLE
Ansible, Chef,  Puppet recipes 

### ISSUE THREAD

**Issue by sonicaghi** [Kong/getkong.org#191]
here below logos to put in the /install page of **getkong.org** 

![ansible_logo](https://cloud.githubusercontent.com/assets/1213643/12402957/68e97026-bde5-11e5-9e7d-314c351e73d0.png)

---

![imgres](https://cloud.githubusercontent.com/assets/1213643/12402960/6c39c5a0-bde5-11e5-811d-3bb5559da5e5.png)

---

![imgres-1](https://cloud.githubusercontent.com/assets/1213643/12402965/75cd3fb6-bde5-11e5-9c95-87ba28fc7f67.png)

---

**Comment by sinzone** [comment]
Resources:

*Puppet*
https://github.com/mybuilder/puppet-kongfig
https://github.com/scottefein/puppet-nyt-kong

**Comment by sinzone** [comment]
also @hutchic may want to check those.

**Comment by sinzone** [comment]
ping

**Comment by ahmadnassri** [comment]
@hutchic need your help on those.

**Comment by coopr** [comment]
Closing as stale.
