### ISSUE TITLE
update Kong logo

### ISSUE THREAD

**Issue by sonicaghi** [Kong/getkong.org#248]

**Comment by sinzone** [comment]
cc @jitachi

**Comment by jitachi** [comment]
After KGG website we're going to invest time in doing the product logos (including favicons and illustrations for the homepage) until that moment, I can't provide assets.

**Comment by darrenjennings** [comment]
https://github.com/Kong/getkong.org/pull/615 will update favicon. Should be good to close this ticket after merging.
