### ISSUE TITLE
bu using values such as 0.0.0.0:8001.

### ISSUE THREAD

**Issue by kswen** [Kong/getkong.org#644]
There`s description in section https://getkong.org/docs/0.13.x/secure-admin-api/#minimal-listening-footprint, which last sentence is "bu using values such as 0.0.0.0:8001." 

Is that "**bu**" suppose to be "**be**"?

**Comment by thibaultcha** [comment]
That should say "by" - mind opening a PR to fix it? Thanks!

**Comment by kswen** [comment]
sure, I will do it later
