### ISSUE TITLE
Kong EE 0.31 Developer Portal authentication doc is broken 

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [Kong/getkong.org#709]
- `getkong.org` url(s):

### Summary

Kong EE 0.31 Developer Portal authentication doc is broken 

### Steps To Reproduce

1. Install kong on server
2. Enable developer portal in kong.conf
3. Run kong
4. Try to add authentication using docs:
https://getkong.org/docs/enterprise/0.31-x/developer-portal/authentication/
5. You will fail on the first steps due to absent api endpoints, eg.
```root@host:~# curl -i -X POST \
>   --url http://127.0.0.1:8001/services/ \
>   --data 'name=portal-files' \
>   --data 'url=http://127.0.0.1:8004'
HTTP/1.1 404 Not Found
Date: Wed, 16 May 2018 14:58:13 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.31-1-enterprise-edition

{"message":"Not found"}
root@host:~#
```

### Additional Details

I assume it is related to https://getkong.org/docs/enterprise/changelog/#0-31
Kong EE 0.31 is based on Kong CE 0.12 which don't have already services and routes apis, the apis comes with Kong CE 0.13 - due to documentation and release notes
https://github.com/Kong/kong/blob/master/CHANGELOG.md#0130---20180322

**Comment by catfishbluefish** [comment]
The docs have been updated to reflect posting to the apis url:
`curl -i -X POST \
  --url http://127.0.0.1:8001/apis/ \
  --data 'name=portal-files' \
  --data 'upstream_url=http://127.0.0.1:8004' \
  --data 'uris=/portal'`
