### ISSUE TITLE
add a search bar

### ISSUE THREAD

**Issue by ahmadnassri** [Kong/getkong.org#71]
keeping it simple: link to Google search with "site:getkong.org SEARCH_TERM"

**Comment by thibaultCha** [comment]
I'm not against it but just wanted to say that I hate search bars who just redirect you to google *pukes*. Makes me feel betrayed.

**Comment by ahmadnassri** [comment]
I just don't want us to waste time on re-inventing the wheel on search or even in implement a UI for a 3rd party search widget

**Comment by thefosk** [comment]
https://swiftype.com

**Comment by sinzone** [comment]
algolia

**Comment by ahmadnassri** [comment]
was gonna do this, but:

swifttype: we've reached the limit on the pro plan ... has to be upgraded. @thefosk 
algolia: is not plug-and-play, require serializing data and sending data dumps to server @sinzone

**Comment by ahmadnassri** [comment]
[google site search](https://www.google.ca/work/search/products/gss.html) is actually cheaper.

**Comment by sinzone** [comment]
swyftye too expesnive, algolia is the best but requires tuning, google a bit meh.

**Comment by ahmadnassri** [comment]
algolia is 100% manual setup (might as well use our own Elastic)

-- 

Ahmad Nassri

**Comment by ahmadnassri** [comment]
@theetrain when ready to look at this, ping me for swifttype credentials.

**Comment by darrenjennings** [comment]
closed by #613

**Comment by thibaultcha** [comment]
@darrenjennings :tada: Bravo!
